import fs from 'node:fs'
import { faker } from '@faker-js/faker'
import { type PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'
import { UniqueEnforcer } from 'enforce-unique'
import { getTopEntries } from "#app/routes/media+/mal.jsx"
import { getTMDBTrending } from "#app/routes/media+/tmdb.jsx"
import { prisma } from '#app/utils/db.server.ts'

const uniqueUsernameEnforcer = new UniqueEnforcer()

export function createUser() {
	const firstName = faker.person.firstName()
	const lastName = faker.person.lastName()

	const username = uniqueUsernameEnforcer
		.enforce(() => {
			return (
				faker.string.alphanumeric({ length: 2 }) +
				'_' +
				faker.internet.userName({
					firstName: firstName.toLowerCase(),
					lastName: lastName.toLowerCase(),
				})
			)
		})
		.slice(0, 20)
		.toLowerCase()
		.replace(/[^a-z0-9_]/g, '_')
	return {
		username,
		name: `${firstName} ${lastName}`,
		email: `${username}@example.com`,
	}
}

export function createPassword(password: string = faker.internet.password()) {
	return {
		hash: bcrypt.hashSync(password, 10),
	}
}

let noteImages: Array<Awaited<ReturnType<typeof img>>> | undefined
export async function getNoteImages() {
	if (noteImages) return noteImages

	noteImages = await Promise.all([
		img({
			altText: 'a nice country house',
			filepath: './tests/fixtures/images/notes/0.png',
		}),
		img({
			altText: 'a city scape',
			filepath: './tests/fixtures/images/notes/1.png',
		}),
		img({
			altText: 'a sunrise',
			filepath: './tests/fixtures/images/notes/2.png',
		}),
		img({
			altText: 'a group of friends',
			filepath: './tests/fixtures/images/notes/3.png',
		}),
		img({
			altText: 'friends being inclusive of someone who looks lonely',
			filepath: './tests/fixtures/images/notes/4.png',
		}),
		img({
			altText: 'an illustration of a hot air balloon',
			filepath: './tests/fixtures/images/notes/5.png',
		}),
		img({
			altText:
				'an office full of laptops and other office equipment that look like it was abandoned in a rush out of the building in an emergency years ago.',
			filepath: './tests/fixtures/images/notes/6.png',
		}),
		img({
			altText: 'a rusty lock',
			filepath: './tests/fixtures/images/notes/7.png',
		}),
		img({
			altText: 'something very happy in nature',
			filepath: './tests/fixtures/images/notes/8.png',
		}),
		img({
			altText: `someone at the end of a cry session who's starting to feel a little better.`,
			filepath: './tests/fixtures/images/notes/9.png',
		}),
	])

	return noteImages
}

let userImages: Array<Awaited<ReturnType<typeof img>>> | undefined
export async function getUserImages() {
	if (userImages) return userImages

	userImages = await Promise.all(
		Array.from({ length: 10 }, (_, index) =>
			img({ filepath: `./tests/fixtures/images/user/${index}.jpg` }),
		),
	)

	return userImages
}

export async function img({
	altText,
	filepath,
}: {
	altText?: string
	filepath: string
}) {
	return {
		altText,
		contentType: filepath.endsWith('.png') ? 'image/png' : 'image/jpeg',
		blob: await fs.promises.readFile(filepath),
	}
}

export async function cleanupDb(prisma: PrismaClient) {
	const tables = await prisma.$queryRaw<
		{ name: string }[]
	>`SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '_prisma_migrations';`

	await prisma.$transaction([
		// Disable FK constraints to avoid relation conflicts during deletion
		prisma.$executeRawUnsafe(`PRAGMA foreign_keys = OFF`),
		// Delete all rows from each table, preserving table structures
		...tables.map(({ name }) =>
			prisma.$executeRawUnsafe(`DELETE from "${name}"`),
		),
		prisma.$executeRawUnsafe(`PRAGMA foreign_keys = ON`),
	])
}

export async function randomWatchlists(listTypes: any[], userId: string, fetchData: boolean) {
  let typeCounts = {
    liveActionCount: 1,
    animeCount: 1,
    mangaCount: 1,
  }

  let typeEntryCounts = {
    liveActionEntryCount: 1,
    animeEntryCount: 1,
    mangaEntryCount: 1,
  }
  
  for (let i = 0; i < faker.number.int({ min: 1, max: 7 }); i++) {
    const chosenType = listTypes[Math.floor(Math.random() * listTypes.length)]
    const listName = faker.lorem.sentence()
    const formattedHeader = `${chosenType.header.charAt(0).toLowerCase()}${chosenType.header.slice(1).replace(/\W/g, '')}`
    const watchlistId = faker.string.uuid()

    await prisma.watchlist.create({
      data: {
        id: watchlistId,
        position: typeCounts[`${formattedHeader}Count` as keyof typeof typeCounts],
        name: listName,
        header: listName.replace(/\W/g, '').toLowerCase(),
        typeId: chosenType.id,
        displayedColumns: chosenType.columns,
        description: faker.lorem.paragraphs(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        ownerId: userId,
      },
    })

    let resultInfo: any
    if (fetchData == true) {
      if (chosenType.name == "liveaction") {
        resultInfo = await getTMDBTrending("movie", 50)
      }
      else if (chosenType.name == "anime") {
        resultInfo = await getTopEntries("anime", "bypopularity", 50)
      }
      else if (chosenType.name == "manga") {
        resultInfo = await getTopEntries("manga", "bypopularity", 50)
      }

      if (!resultInfo || resultInfo.length < 1) {
        continue
      }
    }
    else {
      if (chosenType.name == "liveaction") {
        resultInfo = [
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg|https://www.themoviedb.org/movie/278","title":"The Shawshank Redemption","type":"Movie","airYear":"1994","releaseStart":780278400000,"releaseEnd":780278400000,"nextRelease":"null","length":"2h 22m","rating":"R","genres":"Drama, Crime","language":"English","description":"Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg|https://www.themoviedb.org/movie/424","title":"Schindler's List","type":"Movie","airYear":"1993","releaseStart":755913600000,"releaseEnd":755913600000,"nextRelease":"null","length":"3h 15m","rating":"","genres":"Drama, History, War","language":"English","description":"The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg|https://www.themoviedb.org/movie/389","title":"12 Angry Men","type":"Movie","airYear":"1957","releaseStart":-401673600000,"releaseEnd":-401673600000,"nextRelease":"null","length":"1h 37m","rating":"NR","genres":"Drama","language":"English","description":"The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg|https://www.themoviedb.org/movie/497","title":"The Green Mile","type":"Movie","airYear":"1999","releaseStart":944784000000,"releaseEnd":944784000000,"nextRelease":"null","length":"3h 9m","rating":"R","genres":"Fantasy, Drama, Crime","language":"English","description":"A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg|https://www.themoviedb.org/movie/769","title":"GoodFellas","type":"Movie","airYear":"1990","releaseStart":653097600000,"releaseEnd":653097600000,"nextRelease":"null","length":"2h 25m","rating":"R","genres":"Drama, Crime","language":"English","description":"The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg|https://www.themoviedb.org/movie/346","title":"Seven Samurai","type":"Movie","airYear":"1954","releaseStart":-494985600000,"releaseEnd":-494985600000,"nextRelease":"null","length":"3h 27m","rating":"","genres":"Action, Drama","language":"Japanese","description":"A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg|https://www.themoviedb.org/movie/11216","title":"Cinema Paradiso","type":"Movie","airYear":"1988","releaseStart":595728000000,"releaseEnd":595728000000,"nextRelease":"null","length":"2h 4m","rating":"PG","genres":"Drama, Romance","language":"Italian","description":"A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/74hLDKjD5aGYOotO6esUVaeISa2.jpg|https://www.themoviedb.org/movie/637","title":"Life Is Beautiful","type":"Movie","airYear":"1997","releaseStart":882576000000,"releaseEnd":882576000000,"nextRelease":"null","length":"1h 56m","rating":"PG-13","genres":"Comedy, Drama","language":"Italian","description":"A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg|https://www.themoviedb.org/movie/157336","title":"Interstellar","type":"Movie","airYear":"2014","releaseStart":1415145600000,"releaseEnd":1415145600000,"nextRelease":"null","length":"2h 49m","rating":"PG-13","genres":"Adventure, Drama, Science Fiction","language":"English","description":"The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg|https://www.themoviedb.org/movie/598","title":"City of God","type":"Movie","airYear":"2002","releaseStart":1030665600000,"releaseEnd":1030665600000,"nextRelease":"null","length":"2h 10m","rating":"","genres":"Drama, Crime","language":"Portuguese","description":"In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg|https://www.themoviedb.org/movie/510","title":"One Flew Over the Cuckoo's Nest","type":"Movie","airYear":"1975","releaseStart":185587200000,"releaseEnd":185587200000,"nextRelease":"null","length":"2h 13m","rating":"R","genres":"Drama","language":"English","description":"A petty criminal fakes insanity to serve his sentence in a mental ward rather than prison. He soon finds himself as a leader to the other patients—and an enemy to the cruel, domineering nurse who runs the ward."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg|https://www.themoviedb.org/movie/423","title":"The Pianist","type":"Movie","airYear":"2002","releaseStart":1032220800000,"releaseEnd":1032220800000,"nextRelease":"null","length":"2h 30m","rating":"R","genres":"Drama, War","language":"English","description":"The true story of pianist Władysław Szpilman's experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg|https://www.themoviedb.org/tv/94605","title":"Arcane","type":"TV Series","airYear":"2021","releaseStart":1636156800000,"releaseEnd":1637366400000,"nextRelease":"null","length":"9 eps","rating":"TV-14","genres":"Animation, Drama, Sci-Fi & Fantasy, Action & Adventure","language":"English","description":"Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg|https://www.themoviedb.org/tv/87108","title":"Chernobyl","type":"TV Series","airYear":"2019","releaseStart":1557100800000,"releaseEnd":1559520000000,"nextRelease":"null","length":"5 eps","rating":"NR","genres":"Drama","language":"English","description":"The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg|https://www.themoviedb.org/tv/1398","title":"The Sopranos","type":"TV Series","airYear":"1999","releaseStart":915926400000,"releaseEnd":1181433600000,"nextRelease":"null","length":"86 eps","rating":"TV-MA","genres":"Drama","language":"English","description":"The story of New Jersey-based Italian-American mobster Tony Soprano and the difficulties he faces as he tries to balance the conflicting requirements of his home life and the criminal organization he heads. Those difficulties are often highlighted through his ongoing professional relationship with psychiatrist Jennifer Melfi. The show features Tony's family members and Mafia associates in prominent roles and story arcs, most notably his wife Carmela and his cousin and protégé Christopher Moltisanti."},
          {"thumbnail":"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg|https://www.themoviedb.org/tv/100088","title":"The Last of Us","type":"TV Series","airYear":"2023","releaseStart":1673740800000,"releaseEnd":1678579200000,"nextRelease":"null","length":"9 eps","rating":"TV-MA","genres":"Drama","language":"English","description":"Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival."}
        ]
      }
      else if (chosenType.name == "anime") {
        resultInfo = [
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/1015/138006l.webp|https://myanimelist.net/anime/52991","title":"Sousou no Frieren","type":"TV Series","startSeason":"Fall 2023","releaseStart":1695945600000,"releaseEnd":1711065600000,"nextRelease":null,"length":"28 eps","rating":"PG-13","genres":"Adventure, Drama, Fantasy, Shounen","studios":"[\"Madhouse|https://myanimelist.net/anime/producer/11\"]","priority":"Low","description":"During their decade-long quest to defeat the Demon King, the members of the hero's party—Himmel himself, the priest Heiter, the dwarf warrior Eisen, and the elven mage Frieren—forge bonds through adventures and battles, creating unforgettable precious memories for most of them.\n\nHowever, the time that Frieren spends with her comrades is equivalent to merely a fraction of her life, which has lasted over a thousand years. When the party disbands after their victory, Frieren casually returns to her \"usual\" routine of collecting spells across the continent. Due to her different sense of time, she seemingly holds no strong feelings toward the experiences she went through.\n\nAs the years pass, Frieren gradually realizes how her days in the hero's party truly impacted her. Witnessing the deaths of two of her former companions, Frieren begins to regret having taken their presence for granted; she vows to better understand humans and create real personal connections. Although the story of that once memorable journey has long ended, a new tale is about to begin.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/1208/94745l.jpg|https://myanimelist.net/anime/5114","title":"Fullmetal Alchemist: Brotherhood","type":"TV Series","startSeason":"Spring 2009","releaseStart":1238889600000,"releaseEnd":1278201600000,"nextRelease":null,"length":"64 eps","rating":"R","genres":"Action, Adventure, Drama, Fantasy, Military, Shounen","studios":"[\"Bones|https://myanimelist.net/anime/producer/4\"]","priority":"Low","description":"After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality. Ignoring the alchemical principle banning human transmutation, the boys attempted to bring their recently deceased mother back to life. Instead, they suffered brutal personal loss: Alphonse's body disintegrated while Edward lost a leg and then sacrificed an arm to keep Alphonse's soul in the physical realm by binding it to a hulking suit of armor.\n\nThe brothers are rescued by their neighbor Pinako Rockbell and her granddaughter Winry. Known as a bio-mechanical engineering prodigy, Winry creates prosthetic limbs for Edward by utilizing \"automail,\" a tough, versatile metal used in robots and combat armor. After years of training, the Elric brothers set off on a quest to restore their bodies by locating the Philosopher's Stone—a powerful gem that allows an alchemist to defy the traditional laws of Equivalent Exchange.\n\nAs Edward becomes an infamous alchemist and gains the nickname \"Fullmetal,\" the boys' journey embroils them in a growing conspiracy that threatens the fate of the world.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/1935/127974l.jpg|https://myanimelist.net/anime/9253","title":"Steins;Gate","type":"TV Series","startSeason":"Spring 2011","releaseStart":1302048000000,"releaseEnd":1315958400000,"nextRelease":null,"length":"24 eps","rating":"PG-13","genres":"Drama, Psychological, Sci-Fi, Suspense, Time Travel","studios":"[\"White Fox|https://myanimelist.net/anime/producer/314\"]","priority":"Low","description":"Eccentric scientist Rintarou Okabe has a never-ending thirst for scientific exploration. Together with his ditzy but well-meaning friend Mayuri Shiina and his roommate Itaru Hashida, Okabe founds the Future Gadget Laboratory in the hopes of creating technological innovations that baffle the human psyche. Despite claims of grandeur, the only notable \"gadget\" the trio have created is a microwave that has the mystifying power to turn bananas into green goo.\n\nHowever, when Okabe attends a conference on time travel, he experiences a series of strange events that lead him to believe that there is more to the \"Phone Microwave\" gadget than meets the eye. Apparently able to send text messages into the past using the microwave, Okabe dabbles further with the \"time machine,\" attracting the ire and attention of the mysterious organization SERN.\n\nDue to the novel discovery, Okabe and his friends find themselves in an ever-present danger. As he works to mitigate the damage his invention has caused to the timeline, Okabe fights a battle to not only save his loved ones but also to preserve his degrading sanity.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/3/72078l.jpg|https://myanimelist.net/anime/28977","title":"Gintama°","type":"TV Series","startSeason":"Spring 2015","releaseStart":1428451200000,"releaseEnd":1459296000000,"nextRelease":null,"length":"51 eps","rating":"PG-13","genres":"Action, Comedy, Gag Humor, Historical, Parody, Samurai, Sci-Fi, Shounen","studios":"[\"Bandai Namco Pictures|https://myanimelist.net/anime/producer/1258\"]","priority":"Low","description":"Gintoki, Shinpachi, and Kagura return as the fun-loving but broke members of the Yorozuya team! Living in an alternate-reality Edo, where swords are prohibited and alien overlords have conquered Japan, they try to thrive on doing whatever work they can get their hands on. However, Shinpachi and Kagura still haven't been paid... Does Gin-chan really spend all that cash playing pachinko?\n\nMeanwhile, when Gintoki drunkenly staggers home one night, an alien spaceship crashes nearby. A fatally injured crew member emerges from the ship and gives Gintoki a strange, clock-shaped device, warning him that it is incredibly powerful and must be safeguarded. Mistaking it for his alarm clock, Gintoki proceeds to smash the device the next morning and suddenly discovers that the world outside his apartment has come to a standstill. With Kagura and Shinpachi at his side, he sets off to get the device fixed; though, as usual, nothing is ever that simple for the Yorozuya team.\n\nFilled with tongue-in-cheek humor and moments of heartfelt emotion, Gintama's fourth season finds Gintoki and his friends facing both their most hilarious misadventures and most dangerous crises yet.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/1337/99013l.jpg|https://myanimelist.net/anime/11061","title":"Hunter x Hunter (2011)","type":"TV Series","startSeason":"Fall 2011","releaseStart":1317513600000,"releaseEnd":1411516800000,"nextRelease":null,"length":"148 eps","rating":"PG-13","genres":"Action, Adventure, Fantasy, Shounen","studios":"[\"Madhouse|https://myanimelist.net/anime/producer/11\"]","priority":"Low","description":"Hunters devote themselves to accomplishing hazardous tasks, all from traversing the world's uncharted territories to locating rare items and monsters. Before becoming a Hunter, one must pass the Hunter Examination—a high-risk selection process in which most applicants end up handicapped or worse, deceased.\n\nAmbitious participants who challenge the notorious exam carry their own reason. What drives 12-year-old Gon Freecss is finding Ging, his father and a Hunter himself. Believing that he will meet his father by becoming a Hunter, Gon takes the first step to walk the same path.\n\nDuring the Hunter Examination, Gon befriends the medical student Leorio Paladiknight, the vindictive Kurapika, and ex-assassin Killua Zoldyck. While their motives vastly differ from each other, they band together for a common goal and begin to venture into a perilous world.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/1908/135431l.jpg|https://myanimelist.net/anime/41467","title":"Bleach: Sennen Kessen-hen","type":"TV Series","startSeason":"Fall 2022","releaseStart":1665446400000,"releaseEnd":1672099200000,"nextRelease":null,"length":"13 eps","rating":"R","genres":"Action, Adventure, Fantasy, Shounen","studios":"[\"Pierrot|https://myanimelist.net/anime/producer/1\"]","priority":"Low","description":"Substitute Soul Reaper Ichigo Kurosaki spends his days fighting against Hollows, dangerous evil spirits that threaten Karakura Town. Ichigo carries out his quest with his closest allies: Orihime Inoue, his childhood friend with a talent for healing; Yasutora Sado, his high school classmate with superhuman strength; and Uryuu Ishida, Ichigo's Quincy rival.\n\nIchigo's vigilante routine is disrupted by the sudden appearance of Asguiaro Ebern, a dangerous Arrancar who heralds the return of Yhwach, an ancient Quincy king. Yhwach seeks to reignite the historic blood feud between Soul Reaper and Quincy, and he sets his sights on erasing both the human world and the Soul Society for good.\n\nYhwach launches a two-pronged invasion into both the Soul Society and Hueco Mundo, the home of Hollows and Arrancar. In retaliation, Ichigo and his friends must fight alongside old allies and enemies alike to end Yhwach's campaign of carnage before the world itself comes to an end.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/1295/106551l.jpg|https://myanimelist.net/anime/37999","title":"Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen","type":"TV Series","startSeason":"Winter 2019","releaseStart":1547251200000,"releaseEnd":1553904000000,"nextRelease":null,"length":"12 eps","rating":"PG-13","genres":"Comedy, Psychological, Romantic Subtext, School, Seinen","studios":"[\"A-1 Pictures|https://myanimelist.net/anime/producer/56\"]","priority":"Low","description":"At the renowned Shuchiin Academy, Miyuki Shirogane and Kaguya Shinomiya are the student body's top representatives. Ranked the top student in the nation and respected by peers and mentors alike, Miyuki serves as the student council president. Alongside him, the vice president Kaguya—eldest daughter of the wealthy Shinomiya family—excels in every field imaginable. They are the envy of the entire student body, regarded as the perfect couple.\n\nHowever, despite both having already developed feelings for the other, neither are willing to admit them. The first to confess loses, will be looked down upon, and will be considered the lesser. With their honor and pride at stake, Miyuki and Kaguya are both equally determined to be the one to emerge victorious on the battlefield of love!\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/1447/99827l.jpg|https://myanimelist.net/anime/38680","title":"Fruits Basket 1st Season","type":"TV Series","startSeason":"Spring 2019","releaseStart":1554508800000,"releaseEnd":1569024000000,"nextRelease":null,"length":"25 eps","rating":"PG-13","genres":"Drama, Love Polygon, Romance, School, Shoujo, Supernatural","studios":"[\"TMS Entertainment|https://myanimelist.net/anime/producer/73\"]","priority":"Low","description":"Tooru Honda has always been fascinated by the story of the Chinese zodiac that her beloved mother told her as a child. However, a sudden family tragedy changes her life, and subsequent circumstances leave her all alone. Tooru is now forced to live in a tent, but little does she know that her temporary home resides on the private property of the esteemed Souma family. Stumbling upon their home one day, she encounters Shigure, an older Souma cousin, and Yuki, the \"prince\" of her school. Tooru explains that she lives nearby, but the Soumas eventually discover her well-kept secret of being homeless when they see her walking back to her tent one night.\n\nThings start to look up for Tooru as they kindly offer to take her in after hearing about her situation. But soon after, she is caught up in a fight between Yuki and his hot-tempered cousin, Kyou. While trying to stop them, she learns that the Souma family has a well-kept secret of their own: whenever they are hugged by a member of the opposite sex, they transform into the animals of the Chinese zodiac.\n\nWith this new revelation, Tooru will find that living with the Soumas is an unexpected adventure filled with laughter and romance.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/1299/110774l.jpg|https://myanimelist.net/anime/4181","title":"Clannad: After Story","type":"TV Series","startSeason":"Fall 2008","releaseStart":1222992000000,"releaseEnd":1238112000000,"nextRelease":null,"length":"24 eps","rating":"PG-13","genres":"Drama, Romance, Supernatural","studios":"[\"Kyoto Animation|https://myanimelist.net/anime/producer/2\"]","priority":"Low","description":"Tomoya Okazaki and Nagisa Furukawa have graduated from high school, and together, they experience the emotional rollercoaster of growing up. Unable to decide on a course for his future, Tomoya learns the value of a strong work ethic and discovers the strength of Nagisa's support. Through the couple's dedication and unity of purpose, they push forward to confront their personal problems, deepen their old relationships, and create new bonds.\n\nTime also moves on in the Illusionary World. As the plains grow cold with the approach of winter, the Illusionary Girl and the Garbage Doll are presented with a difficult situation that reveals the World's true purpose.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/3/82899l.jpg|https://myanimelist.net/anime/31646","title":"3-gatsu no Lion","type":"TV Series","startSeason":"Fall 2016","releaseStart":1475884800000,"releaseEnd":1489795200000,"nextRelease":null,"length":"22 eps","rating":"PG-13","genres":"Childcare, Drama, Seinen, Strategy Game","studios":"[\"Shaft|https://myanimelist.net/anime/producer/44\"]","priority":"Low","description":"Having reached professional status in middle school, Rei Kiriyama is one of the few elite in the world of shogi. Due to this, he faces an enormous amount of pressure, both from the shogi community and his adoptive family. Seeking independence from his tense home life, he moves into an apartment in Tokyo. As a 17-year-old living on his own, Rei tends to take poor care of himself, and his reclusive personality ostracizes him from his peers in school and at the shogi hall.\n\nHowever, not long after his arrival in Tokyo, Rei meets Akari, Hinata, and Momo Kawamoto, a trio of sisters living with their grandfather who owns a traditional wagashi shop. Akari, the oldest of the three girls, is determined to combat Rei's loneliness and poorly sustained lifestyle with motherly hospitality. The Kawamoto sisters, coping with past tragedies, also share with Rei a unique familial bond that he has lacked for most of his life. As he struggles to maintain himself physically and mentally through his shogi career, Rei must learn how to interact with others and understand his own complex emotions.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/1708/138033l.jpg|https://myanimelist.net/anime/54492","title":"Kusuriya no Hitorigoto","type":"TV Series","startSeason":"Fall 2023","releaseStart":1697932800000,"releaseEnd":1711238400000,"nextRelease":null,"length":"24 eps","rating":"PG-13","genres":"Drama, Historical, Medical, Mystery","studios":"[\"OLM|https://myanimelist.net/anime/producer/28\",\"TOHO animation STUDIO|https://myanimelist.net/anime/producer/2705\"]","priority":"Low","description":"Maomao, an apothecary's daughter, has been plucked from her peaceful life and sold to the lowest echelons of the imperial court. Now merely a maid, Maomao settles into her new mundane life and hides her extensive knowledge of medicine in order to avoid any unwanted attention.\n\nNot long after Maomao's arrival, the emperor's infant children inexplicably begin to experience grave symptoms—almost as if a curse has been cast. The curious Maomao easily solves the mystery and, to remain out of the limelight, attempts to leave an anonymous tip. Unfortunately, the dashing and perceptive eunuch Jinshi sees through it and manages to single her out.\n\nIn recognition of her talent, Maomao is promoted to lady-in-waiting for the emperor's favorite concubine, Gyokuyou. As Maomao continues to remedy the numerous ailments afflicting the imperial court, her pharmaceutical expertise quickly proves indispensable.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/10/47347l.jpg|https://myanimelist.net/anime/16498","title":"Shingeki no Kyojin","type":"TV Series","startSeason":"Spring 2013","releaseStart":1365292800000,"releaseEnd":1380412800000,"nextRelease":null,"length":"25 eps","rating":"R","genres":"Action, Award Winning, Drama, Gore, Military, Shounen, Survival, Suspense","studios":"[\"Wit Studio|https://myanimelist.net/anime/producer/858\"]","priority":"Low","description":"Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans, forcing humans to hide in fear behind enormous concentric walls. What makes these giants truly terrifying is that their taste for human flesh is not born out of hunger but what appears to be out of pleasure. To ensure their survival, the remnants of humanity began living within defensive barriers, resulting in one hundred years without a single titan encounter. However, that fragile calm is soon shattered when a colossal Titan manages to breach the supposedly impregnable outer wall, reigniting the fight for survival against the man-eating abominations.\n\nAfter witnessing a horrific personal loss at the hands of the invading creatures, Eren Yeager dedicates his life to their eradication by enlisting into the Survey Corps, an elite military unit that combats the merciless humanoids outside the protection of the walls. Eren, his adopted sister Mikasa Ackerman, and his childhood friend Armin Arlert join the brutal war against the Titans and race to discover a way of defeating them before the last walls are breached.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/4/39779l.jpg|https://myanimelist.net/anime/14227","title":"Tonari no Kaibutsu-kun","type":"TV Series","startSeason":"Fall 2012","releaseStart":1349136000000,"releaseEnd":1356393600000,"nextRelease":null,"length":"13 eps","rating":"PG-13","genres":"Comedy, Romance, School, Shoujo","studios":"[\"Brain's Base|https://myanimelist.net/anime/producer/112\"]","priority":"Low","description":"Shizuku Mizutani is apathetic toward her classmates, only caring about her grades. However, her cold view of life begins to change when she meets Haru Yoshida, a violent troublemaker who stopped attending class after getting into a fight early in the school year. He is not much different from her, though—he too understands little about human nature and does not have any friends. Much to Shizuku's surprise, he proclaims that she will be his friend and immediately confesses his feelings toward her upon meeting her.\n \nBecause of her lack of friends and social interaction, Shizuku has a hard time understanding her relationship with Haru. But slowly, their friendship begins to progress, and she discovers that there is more to Haru than violence. She begins to  develop feelings for him, but is unsure what kind of emotions she is experiencing. Together, Shizuku and Haru explore the true nature of their relationship and emotions.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/1795/95088l.jpg|https://myanimelist.net/anime/33352","title":"Violet Evergarden","type":"TV Series","startSeason":"Winter 2018","releaseStart":1515628800000,"releaseEnd":1522886400000,"nextRelease":null,"length":"13 eps","rating":"PG-13","genres":"Drama, Fantasy","studios":"[\"Kyoto Animation|https://myanimelist.net/anime/producer/2\"]","priority":"Low","description":"The Great War finally came to an end after four long years of conflict; fractured in two, the continent of Telesis slowly began to flourish once again. Caught up in the bloodshed was Violet Evergarden, a young girl raised for the sole purpose of decimating enemy lines. Hospitalized and maimed in a bloody skirmish during the War's final leg, she was left with only words from the person she held dearest, but with no understanding of their meaning.\n\nRecovering from her wounds, Violet starts a new life working at CH Postal Services after a falling out with her new intended guardian family. There, she witnesses by pure chance the work of an \"Auto Memory Doll,\" amanuenses that transcribe people's thoughts and feelings into words on paper. Moved by the notion, Violet begins work as an Auto Memory Doll, a trade that will take her on an adventure, one that will reshape the lives of her clients and hopefully lead to self-discovery.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/1500/103005l.jpg|https://myanimelist.net/anime/37521","title":"Vinland Saga","type":"TV Series","startSeason":"Summer 2019","releaseStart":1562544000000,"releaseEnd":1577664000000,"nextRelease":null,"length":"24 eps","rating":"R","genres":"Action, Adventure, Drama, Gore, Historical, Seinen","studios":"[\"Wit Studio|https://myanimelist.net/anime/producer/858\"]","priority":"Low","description":"Young Thorfinn grew up listening to the stories of old sailors that had traveled the ocean and reached the place of legend, Vinland. It's said to be warm and fertile, a place where there would be no need for fighting—not at all like the frozen village in Iceland where he was born, and certainly not like his current life as a mercenary. War is his home now. Though his father once told him, \"You have no enemies, nobody does. There is nobody who it's okay to hurt,\" as he grew, Thorfinn knew that nothing was further from the truth.\n\nThe war between England and the Danes grows worse with each passing year. Death has become commonplace, and the viking mercenaries are loving every moment of it. Allying with either side will cause a massive swing in the balance of power, and the vikings are happy to make names for themselves and take any spoils they earn along the way. Among the chaos, Thorfinn must take his revenge and kill Askeladd, the man who murdered his father. The only paradise for the vikings, it seems, is the era of war and death that rages on.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/anime/8/80356l.jpg|https://myanimelist.net/anime/32182","title":"Mob Psycho 100","type":"TV Series","startSeason":"Summer 2016","releaseStart":1468195200000,"releaseEnd":1474934400000,"nextRelease":null,"length":"12 eps","rating":"PG-13","genres":"Action, Comedy, Super Power, Supernatural","studios":"[\"Bones|https://myanimelist.net/anime/producer/4\"]","priority":"Low","description":"Eighth-grader Shigeo \"Mob\" Kageyama has tapped into his inner wellspring of psychic prowess at a young age. But the power quickly proves to be a liability when he realizes the potential danger in his skills. Choosing to suppress his power, Mob's only present use for his ability is to impress his longtime crush, Tsubomi, who soon grows bored of the same tricks.\n\nIn order to effectuate control on his skills, Mob enlists himself under the wing of Arataka Reigen, a con artist claiming to be a psychic, who exploits Mob's powers for pocket change. Now, exorcising evil spirits on command has become a part of Mob's daily, monotonous life. However, the psychic energy he exerts is barely the tip of the iceberg; if his vast potential and unrestrained emotions run berserk, a cataclysmic event that would render him completely unrecognizable will be triggered. The progression toward Mob's explosion is rising and attempting to stop it is futile.\n\n[Written by MAL Rewrite]"}
        ]
      }
      else if (chosenType.name == "manga") {
        resultInfo = [
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/1/157897l.jpg|https://myanimelist.net/manga/2","title":"Berserk","type":"Manga","startYear":"1989","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"0","volumes":"0","genres":"Action, Adventure, Award Winning, Drama, Fantasy, Gore, Horror, Military, Mythology, Psychological, Seinen, Supernatural","serialization":"[\"Young Animal|https://myanimelist.net/manga/magazine/2\"]","authors":"[\"Kentarou Miura (Story & Art)|https://myanimelist.net/people/1868\",\" Studio Gaga (Art)|https://myanimelist.net/people/49592\"]","priority":"Low","description":"Guts, a former mercenary now known as the \"Black Swordsman,\" is out for revenge. After a tumultuous childhood, he finally finds someone he respects and believes he can trust, only to have everything fall apart when this person takes away everything important to Guts for the purpose of fulfilling his own desires. Now marked for death, Guts becomes condemned to a fate in which he is relentlessly pursued by demonic beings.\n\nSetting out on a dreadful quest riddled with misfortune, Guts, armed with a massive sword and monstrous strength, will let nothing stop him, not even death itself, until he is finally able to take the head of the one who stripped him—and his loved one—of their humanity.\n\n[Written by MAL Rewrite]\n\nIncluded one-shot:\nVolume 14: Berserk: The Prototype"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/3/179882l.jpg|https://myanimelist.net/manga/1706","title":"JoJo no Kimyou na Bouken Part 7: Steel Ball Run","type":"Manga","startYear":"2004","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"96","volumes":"24","genres":"Action, Adventure, Historical, Mystery, Seinen, Shounen, Supernatural","serialization":"[\"Ultra Jump|https://myanimelist.net/manga/magazine/25\"]","authors":"[\"Hirohiko Araki (Story & Art)|https://myanimelist.net/people/2619\"]","priority":"Low","description":"In the American Old West, the world's greatest race is about to begin. Thousands line up in San Diego to travel over six thousand kilometers for a chance to win the grand prize of fifty million dollars. With the era of the horse reaching its end, contestants are allowed to use any kind of vehicle they wish. Competitors will have to endure grueling conditions, traveling up to a hundred kilometers a day through uncharted wastelands. The Steel Ball Run is truly a one-of-a-kind event.\n\nThe youthful Johnny Joestar, a crippled former horse racer, has come to San Diego to watch the start of the race. There he encounters Gyro Zeppeli, a racer with two steel balls at his waist instead of a gun. Johnny witnesses Gyro using one of his steel balls to unleash a fantastical power, compelling a man to fire his gun at himself during a duel. In the midst of the action, Johnny happens to touch the steel ball and feels a power surging through his legs, allowing him to stand up for the first time in two years. Vowing to find the secret of the steel balls, Johnny decides to compete in the race, and so begins his bizarre adventure across America on the Steel Ball Run.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/1/259070l.jpg|https://myanimelist.net/manga/656","title":"Vagabond","type":"Manga","startYear":"1998","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"327","volumes":"37","genres":"Action, Adventure, Award Winning, Historical, Samurai, Seinen","serialization":"[\"Morning|https://myanimelist.net/manga/magazine/72\"]","authors":"[\"Takehiko Inoue (Story & Art)|https://myanimelist.net/people/1911\",\"Eiji Yoshikawa (Story)|https://myanimelist.net/people/5760\"]","priority":"Low","description":"In 16th-century Japan, Shinmen Takezou is a wild, rough young man, in both his appearance and his actions. His aggressive nature has won him the collective reproach and fear of his village, leading him and his best friend, Matahachi Honiden, to run away in search of something grander than provincial life. The pair enlist in the Toyotomi army, yearning for glory—but when the Toyotomi suffer a crushing defeat at the hands of the Tokugawa Clan at the Battle of Sekigahara, the friends barely make it out alive.\n\nAfter the two are separated, Shinmen returns home on a self-appointed mission to notify the Hon'iden family of Matahachi's survival. He instead finds himself a wanted criminal, framed for his friend's supposed murder based on his history of violence. Upon being captured, he is strung up on a tree and left to die. An itinerant monk, the distinguished Takuan Soho, takes pity on the \"devil child,\" secretly freeing Shinmen and christening him with a new name to avoid pursuit by the authorities: Musashi Miyamoto.\n\nVagabond is the fictitious retelling of the life of one of Japan's most renowned swordsmen, the \"Sword Saint\" Musashi Miyamoto—his rise from a swordsman with no desire other than to become \"Invincible Under the Heavens\" to an enlightened warrior who slowly learns of the importance of close friends, self-reflection, and life itself.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/2/253146l.jpg|https://myanimelist.net/manga/13","title":"One Piece","type":"Manga","startYear":"1997","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"0","volumes":"0","genres":"Action, Adventure, Fantasy, Shounen","serialization":"[\"Shounen Jump (Weekly)|https://myanimelist.net/manga/magazine/83\"]","authors":"[\"Eiichiro Oda (Story & Art)|https://myanimelist.net/people/1881\"]","priority":"Low","description":"Gol D. Roger, a man referred to as the \"King of the Pirates,\" is set to be executed by the World Government. But just before his demise, he confirms the existence of a great treasure, One Piece, located somewhere within the vast ocean known as the Grand Line. Announcing that One Piece can be claimed by anyone worthy enough to reach it, the King of the Pirates is executed and the Great Age of Pirates begins.\n\nTwenty-two years later, a young man by the name of Monkey D. Luffy is ready to embark on his own adventure, searching for One Piece and striving to become the new King of the Pirates. Armed with just a straw hat, a small boat, and an elastic body, he sets out on a fantastic journey to gather his own crew and a worthy ship that will take them across the Grand Line to claim the greatest status on the high seas.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/3/258224l.jpg|https://myanimelist.net/manga/1","title":"Monster","type":"Manga","startYear":"1994","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"162","volumes":"18","genres":"Adult Cast, Award Winning, Drama, Mystery, Psychological, Seinen","serialization":"[\"Big Comic Original|https://myanimelist.net/manga/magazine/1\"]","authors":"[\"Naoki Urasawa (Story & Art)|https://myanimelist.net/people/1867\"]","priority":"Low","description":"Kenzou Tenma, a renowned Japanese neurosurgeon working in post-war Germany, faces a difficult choice: to operate on Johan Liebert, an orphan boy on the verge of death, or on the mayor of Düsseldorf. In the end, Tenma decides to gamble his reputation by saving Johan, effectively leaving the mayor for dead.\n\nAs a consequence of his actions, hospital director Heinemann strips Tenma of his position, and Heinemann's daughter Eva breaks off their engagement. Disgraced and shunned by his colleagues, Tenma loses all hope of a successful career—that is, until the mysterious killing of Heinemann gives him another chance.\n\nNine years later, Tenma is the head of the surgical department and close to becoming the director himself. Although all seems well for him at first, he soon becomes entangled in a chain of gruesome murders that have taken place throughout Germany. The culprit is a monster—the same one that Tenma saved on that fateful day nine years ago.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/2/258749l.jpg|https://myanimelist.net/manga/51","title":"Slam Dunk","type":"Manga","startYear":"1990","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"276","volumes":"31","genres":"Award Winning, School, Shounen, Sports, Team Sports","serialization":"[\"Shounen Jump (Weekly)|https://myanimelist.net/manga/magazine/83\"]","authors":"[\"Takehiko Inoue (Story & Art)|https://myanimelist.net/people/1911\"]","priority":"Low","description":"Hanamichi Sakuragi, a tall, boisterous teenager with flame-red hair and physical strength beyond his years, is eager to put an end to his rejection streak of 50 and finally score a girlfriend as he begins his first year of Shohoku High. However, his reputation for delinquency and destructiveness precedes him, and most of his fellow students subsequently avoid him like the plague. As his first day of school ends, he is left with two strong thoughts: \"I hate basketball\" and \"I need a girlfriend.\"\n\nHaruko Akagi, ignorant of Hanamichi's history of misbehavior, notices his immense height and unwittingly approaches him, asking whether or not he likes basketball. Overcome by the fact that a girl is speaking to him, the red-haired giant blurts out a yes despite his true feelings. At the gym, Haruko asks if he can do a slam dunk. Though a complete novice, Hanamachi palms the ball and makes the leap...but overshoots, slamming his head into the backboard. Amazed by his near-inhuman physical abilities, Haruko quickly notifies the school's basketball captain of his feat. With this, Hanamichi is unexpectedly thrust into a world of competition for a girl he barely knows, but he soon discovers that there is perhaps more to basketball than he once thought.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/2/166124l.jpg|https://myanimelist.net/manga/70345","title":"Grand Blue","type":"Manga","startYear":"2014","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"0","volumes":"0","genres":"Comedy, Seinen","serialization":"[\"good! Afternoon|https://myanimelist.net/manga/magazine/316\"]","authors":"[\"Kenji Inoue (Story)|https://myanimelist.net/people/7108\",\"Kimitake Yoshioka (Art)|https://myanimelist.net/people/16441\"]","priority":"Low","description":"Among the seaside town of Izu's ocean waves and rays of shining sun, Iori Kitahara is just beginning his freshman year at Izu University. As he moves into his uncle's scuba diving shop, Grand Blue, he eagerly anticipates his dream college life, filled with beautiful girls and good friends.\n\nBut things don't exactly go according to plan. Upon entering the shop, he encounters a group of rowdy, naked upperclassmen, who immediately coerce him into participating in their alcoholic activities. Though unwilling at first, Iori quickly gives in and becomes the heart and soul of the party. Unfortunately, this earns him the scorn of his cousin, Chisa Kotegawa, who walks in at precisely the wrong time. Undeterred, Iori still vows to realize his ideal college life, but will things go according to plan this time, or will his situation take yet another dive?\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/3/266834l.jpg|https://myanimelist.net/manga/4632","title":"Oyasumi Punpun","type":"Manga","startYear":"2007","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"147","volumes":"13","genres":"Drama, Psychological, Seinen, Slice of Life","serialization":"[\"Big Comic Spirits|https://myanimelist.net/manga/magazine/3\"]","authors":"[\"Inio Asano (Story & Art)|https://myanimelist.net/people/2836\"]","priority":"Low","description":"Punpun Onodera is a normal 11-year-old boy living in Japan. Hopelessly idealistic and romantic, Punpun begins to see his life take a subtle—though nonetheless startling—turn to the adult when he meets the new girl in his class, Aiko Tanaka. It is then that the quiet boy learns just how fickle maintaining a relationship can be, and the surmounting difficulties of transitioning from a naïve boyhood to a convoluted adulthood. When his father assaults his mother one night, Punpun realizes another thing: those whom he looked up to were not as impressive as he once thought.\n\nAs his problems increase, Punpun's once shy demeanor turns into voluntary reclusiveness. Rather than curing him of his problems and conflicting emotions, this merely intensifies them, sending him down the dark path of maturity in this grim coming-of-age saga.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/2/171872l.jpg|https://myanimelist.net/manga/16765","title":"Kingdom","type":"Manga","startYear":"2006","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"0","volumes":"0","genres":"Action, Award Winning, Historical, Military, Seinen","serialization":"[\"Young Jump|https://myanimelist.net/manga/magazine/87\"]","authors":"[\"Yasuhisa Hara (Story & Art)|https://myanimelist.net/people/14715\"]","priority":"Low","description":"During the Warring States period in China, Xin and Piao are two brother-like youngsters who dream of becoming Great Generals, despite their low status as orphaned slaves. One day, they encounter a man of nobility, who gives Piao an opportunity to undertake an important duty within the state of Qin's royal palace. Parting ways, Xin and Piao promise each other to one day become the greatest generals in the world. However, after a fierce coup d'état occurs in the palace, Xin meets with a dying Piao, whose last words spur him into action and lead him to encounter the young and soon-to-be king of Qin, Zheng Ying.\n\nAlthough initially on bad terms, Xin and Zheng become comrades and start on a path filled with trials and bloodshed. Zheng's objective is to bring all the warring states under Qin, and Xin seeks to climb to the very top of the army ranks. Against a backdrop of constant tactical battle between states and great political unrest, both outside and within the palace, the two endeavor towards their monumental ambitions that will change history forever.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/1/115443l.jpg|https://myanimelist.net/manga/44489","title":"Houseki no Kuni","type":"Manga","startYear":"2012","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"108","volumes":"13","genres":"Action, Anthropomorphic, Drama, Fantasy, Seinen","serialization":"[\"Afternoon|https://myanimelist.net/manga/magazine/4\"]","authors":"[\"Haruko Ichikawa (Story & Art)|https://myanimelist.net/people/16515\"]","priority":"Low","description":"Long ago, Earth was struck by six meteorites, creating six moons and leaving a lone island in their wake. Those who could not make it to the island sank to the bottom of the ocean, where, over time, they slowly turned to crystal. As countless millennia passed, 28 of these crystallized lifeforms, known as the Lustrous, rose from the depths and resided on the island. Led by the wise Kongou-sensei, they must defend themselves against the seemingly infinite number of Lunarians, inhabitants of the moons who seek to harvest their valuable bodies for crafting weapons and jewelry. \n\nHouseki no Kuni centers around Phosphophyllite, a young gem about to turn three hundred years old. Clumsy, extremely fragile, and having no visible talent, they are one of the weakest gems around, unable to help in the fight against the Lunarians in any meaningful way. But as the battle with the otherworldly invaders rages on, they soon learn that power comes at a cost that no one should have to pay.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/5/259524l.jpg|https://myanimelist.net/manga/104","title":"Yotsuba to!","type":"Manga","startYear":"2003","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"0","volumes":"0","genres":"Award Winning, Childcare, Comedy, Iyashikei, Slice of Life","serialization":"[\"Dengeki Daioh|https://myanimelist.net/manga/magazine/23\"]","authors":"[\"Kiyohiko Azuma (Story & Art)|https://myanimelist.net/people/1939\"]","priority":"Low","description":"While most people find the world mundane, five-year-old Yotsuba Koiwai sees it as a treasure trove of amazing bustle and wonderful places to explore. When she and her adoptive father, Yousuke, move to a new city, the energetic young girl naturally sets out to investigate the neighborhood on her own.\n\nAfter a few incidents at the local park, the Koiwais become acquainted with their neighbors, the Ayase family. Their three daughters—mischievous college student Asagi, responsible high school student Fuuka, and kindhearted grade school student Ena—eventually all take a liking to Yotsuba and join in on her antics, despite their sheer ridicule.\n\nFrom learning how to use a swing to figuring out how to stop global warming with air conditioners, Yotsuba's ability to infallibly find fun in everything, both amazes and annoys the people around her. Along with Yousuke, the Ayases, and friends she makes along the way, Yotsuba embarks on daily adventures, each one a step in her quest to enjoy the simple things in life.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/2/172982l.jpg|https://myanimelist.net/manga/336","title":"GTO","type":"Manga","startYear":"1996","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"208","volumes":"25","genres":"Action, Award Winning, Comedy, Delinquents, Drama, Ecchi, School, Shounen, Workplace","serialization":"[\"Shounen Magazine (Weekly)|https://myanimelist.net/manga/magazine/8\"]","authors":"[\"Tooru Fujisawa (Story & Art)|https://myanimelist.net/people/2318\"]","priority":"Low","description":"22-year-old Eikichi Onizuka: pervert, former gang member... and teacher?\n\nGreat Teacher Onizuka follows the incredible, though often ridiculous, antics of the titular teacher as he attempts to outwit and win over the cunning Class 3-4 that is determined to have him removed from the school. However, other obstacles present themselves throughout—including the frustrated, balding vice principal, Hiroshi Uchiyamada; old enemies from his biker days; and his own idiotic teaching methods. But Eikichi fights it all whilst trying to help his students, romance fellow teacher Azusa Fuyutsuki, and earn his self-proclaimed title.\n\n[Written by MAL Rewrite]\n\nAlso contains the gaiden \"GTO: Great Toroko Oppai♡\" (Tomoko's Big Adventures)."},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/2/258225l.jpg|https://myanimelist.net/manga/35243","title":"Haikyuu!!","type":"Manga","startYear":"2012","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"407","volumes":"45","genres":"Award Winning, School, Shounen, Sports, Team Sports","serialization":"[\"Shounen Jump (Weekly)|https://myanimelist.net/manga/magazine/83\"]","authors":"[\"Haruichi Furudate (Story & Art)|https://myanimelist.net/people/8260\"]","priority":"Low","description":"The whistle blows. The ball is up. A dig. A set. A spike.\n\nVolleyball. A sport where two teams face off, separated by a formidable, wall-like net.\n\nThe \"Little Giant,\" standing at only 170 centimeters, overcomes the towering net and the wall of blockers. The awe-inspired Shouyou Hinata looks on at the ace's crow-like figure. Determined to reach great heights like the Little Giant, small-statured Hinata finally manages to form a team in his last year of junior high school, and enters his first volleyball tournament. However, his team is utterly defeated in their first game against the powerhouse school Kitagawa Daiichi, led by the genius, but oppressive setter dubbed the \"King of the Court,\" Tobio Kageyama.\n\nHinata enrolls into Karasuno High School seeking to take revenge against Kageyama in an official high school match and to follow in the Little Giant's footsteps—but his plans are ruined when he opens the gymnasium door to find Kageyama as one of his teammates.\n\nNow, Hinata must establish himself on the team and work alongside the problematic Kageyama to overcome his shortcomings and to fulfill his dream of making it to the top of the high school volleyball world.\n\n[Written by MAL Rewrite]\n\nIncluded one-shot:\nVolume 14: Nisekyuu!!"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/2/269202l.jpg|https://myanimelist.net/manga/21525","title":"Akatsuki no Yona","type":"Manga","startYear":"2009","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"0","volumes":"0","genres":"Action, Adventure, Fantasy, Romance, Shoujo","serialization":"[\"Hana to Yume|https://myanimelist.net/manga/magazine/21\"]","authors":"[\"Mizuho Kusanagi (Story & Art)|https://myanimelist.net/people/2426\"]","priority":"Low","description":"Once upon a time, the kingdom of Kouka was ruled by a red dragon in human form. By his side, four warriors imbued with dragon blood helped him lead the kingdom to prosperity. Time passed, and this tale became a legend to tell children.\n\nAs the sole princess of Kouka, Yona lives a life of lavish ease. In love with her cousin, Su-won, and protected by her bodyguard, Son Hak, she wants for nothing and remains sheltered from the harrowing reality outside the castle walls. Contrary to this peaceful illusion, Kouka is about to undergo a political upheaval. After her beloved Su-won stages a bloody coup and murders her father, Yona is forced to flee with only Hak by her side.\n\nThough surrounded by enemies on all sides, the banished princess still yearns to save her kingdom. Her solution comes from an exiled priest, who tells her that her only hope is to find the four legendary dragon warriors. Guided by this seemingly fictitious myth, Yona sets out to find these warriors, determined to restore her kingdom.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/2/181049l.jpg|https://myanimelist.net/manga/70259","title":"Mushoku Tensei: Isekai Ittara Honki Dasu","type":"Manga","startYear":"2014","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"0","volumes":"0","genres":"Fantasy, Isekai, Reincarnation, Seinen","serialization":"[\"Comic Flapper|https://myanimelist.net/manga/magazine/174\"]","authors":"[\"Yuka Fujikawa (Art)|https://myanimelist.net/people/10353\",\" Rifujin na Magonote (Story)|https://myanimelist.net/people/30675\"]","priority":"Low","description":"A 34-year-old NEET loses his life saving a stranger in a traffic accident, only to wake up to find himself reborn as the baby Rudeus Greyrat in a new world filled with magic. The child of the adventurers Paul and Zenith Greyrat, his innate talent for magic is immediately recognized when he turns two, and the magic tutor Roxy Migurdia is brought to his home to refine him into a mage. With a tremendous amount of magical power and a wealth of knowledge from his original world, Rudeus seeks to fulfill his only desires from his previous life—to not repeat the mistakes of his past and die with no regrets.\n\n[Written by MAL Rewrite]"},
          {"thumbnail":"https://cdn.myanimelist.net/images/manga/1/129447l.jpg|https://myanimelist.net/manga/74697","title":"Re:Zero kara Hajimeru Isekai Seikatsu","type":"Light Novel","startYear":"2014","releaseStart":null,"releaseEnd":null,"nextRelease":null,"chapters":"0","volumes":"0","genres":"Drama, Fantasy, Isekai, Psychological, Suspense, Time Travel","serialization":"[]","authors":"[\"Tappei Nagatsuki (Story)|https://myanimelist.net/people/32649\",\"Shinichirou Ootsuka (Art)|https://myanimelist.net/people/32651\"]","priority":"Low","description":"Exiting the convenience store, Subaru Natsuki emerges to a busy town inhabited by humans and demi-humans. Using dragons and carriages as transportation, the town is clearly not the modern-day Japan that he is familiar with. However, as someone who spends his days engrossed in comics and games, Subaru assumes that he is a protagonist in this new fantasy world, harnessing supreme magical powers.\n\nMuch to his dismay, that is not the case and things quickly go awry as he bumps into a group of thugs. Fortunately, a silver-haired beauty named Satella comes to his rescue, while looking for her stolen insignia. In return for her kindness, Subaru offers to help with the search, which eventually leads them to a loot shop. Assuming that the insignia was traded for money, Subaru enters the shop hoping to negotiate with the owner regarding the stolen item. However, much to his surprise, what awaits them is not the insignia but a brutal assassin that leads the two to their demise.\n\nBut instead of waking up in the afterlife, Subaru is shocked to find himself standing alone in the midst of daytime, as if he never left the town in the first place. Thus, his life in another world mysteriously begins a second time.\n\n[Written by MAL Rewrite]"}
        ]
      }
    }

    if (!resultInfo || resultInfo.length < 1) {
      continue
    }

    for(let j = 0; j < faker.number.int({ min: 1, max: 20 }); j++) {
      const currCount = typeEntryCounts[`${formattedHeader}EntryCount` as keyof typeof typeEntryCounts]
      const currEntry = await resultInfo.splice(Math.floor(Math.random() * resultInfo.length), 1)[0]

      if (chosenType.name == "liveaction") {
        await prisma.liveActionEntry.create({
          data: {
            id: faker.string.uuid(), watchlistId: watchlistId, position: currCount, thumbnail: currEntry?.thumbnail, title: currEntry?.title, type: currEntry?.type, airYear: String(currEntry?.year), releaseStart: currEntry?.releaseStart ? new Date(currEntry?.releaseStart).toISOString() : null, releaseEnd: currEntry?.releaseEnd ? new Date(currEntry?.releaseEnd).toISOString() : null, nextRelease:  JSON.stringify(currEntry?.nextRelease), length: currEntry?.length, rating: currEntry?.rating, history: JSON.stringify({added: Date.now(), started: null, finished: null, progress: null, lastUpdated: Date.now(), }), genres: currEntry?.genres , language: currEntry?.language, story: 0, character: 0, presentation: 0, sound: 0, performance: 0, enjoyment: 0, averaged: 0, personal: 0, differencePersonal: 0, tmdbScore: currEntry?.score, differenceObjective: 0, description: currEntry?.description, notes: ""
          },
        })
      }
      else if (chosenType.name == "anime") {
        await prisma.animeEntry.create({
          data: {
            id: faker.string.uuid(), watchlistId: watchlistId, position: currCount, thumbnail: currEntry?.thumbnail, title: currEntry?.title, type: currEntry?.type, startSeason: currEntry?.startSeason.name, releaseStart: currEntry?.releaseStart ? new Date(currEntry?.releaseStart).toISOString() : null, releaseEnd: currEntry?.releaseEnd ? new Date(currEntry?.releaseEnd).toISOString() : null, nextRelease:  JSON.stringify(currEntry?.nextRelease), length: currEntry?.length, rating: currEntry?.rating, history: JSON.stringify({added: Date.now(), started: null, finished: null, progress: null, lastUpdated: Date.now(), }), genres: currEntry?.genres , studios: JSON.stringify(currEntry?.studios), priority: "Low", story: 0, character: 0, presentation: 0, sound: 0, performance: 0, enjoyment: 0, averaged: 0, personal: 0, differencePersonal: 0, malScore: currEntry?.malScore, differenceObjective: 0, description: currEntry?.description, notes: ""
          },
        })
      }
      else if (chosenType.name == "manga") {
        await prisma.mangaEntry.create({
          data: {
            id: faker.string.uuid(), watchlistId: watchlistId, position: currCount, thumbnail: currEntry?.thumbnail, title: currEntry?.title, type: currEntry?.type, startYear: String(currEntry?.startYear), releaseStart: currEntry?.releaseStart ? new Date(currEntry?.releaseStart).toISOString() : null, releaseEnd: currEntry?.releaseEnd ? new Date(currEntry?.releaseEnd).toISOString() : null, nextRelease:  JSON.stringify(currEntry?.nextRelease), chapters: String(currEntry?.chapters), volumes: String(currEntry?.volumes), history: JSON.stringify({added: Date.now(), started: null, finished: null, progress: null, lastUpdated: Date.now(), }), genres: currEntry?.genres , serialization: JSON.stringify(currEntry?.serialization), authors: JSON.stringify(currEntry?.authors), priority: "Low", story: 0, character: 0, presentation: 0, enjoyment: 0, averaged: 0, personal: 0, differencePersonal: 0, malScore: currEntry?.malScore, differenceObjective: 0, description: currEntry?.description, notes: ""
          },
        })
      }

      typeEntryCounts[`${formattedHeader}EntryCount` as keyof typeof typeEntryCounts]++
    }

    typeCounts[`${formattedHeader}Count` as keyof typeof typeCounts]++
  }
}
