import {
	type RouteConfig,
	type RouteConfigEntry,
} from '@react-router/dev/routes'

type RouteOptions = Omit<RouteConfigEntry, 'file' | 'id'>

/**
 * Keep route IDs stable while defining the route tree directly in React Router.
 * The IDs intentionally match the IDs generated by the previous flat-routes
 * adapter because several parts of React Router expose them through matches and
 * the server manifest.
 */
function appRoute(file: string, options: RouteOptions = {}): RouteConfigEntry {
	return {
		id: file.replace(/\.[^/.]+$/, ''),
		file,
		...options,
	}
}

export default [
	appRoute('routes/$.tsx', { path: '*' }),
	appRoute('routes/_auth+/auth.$provider.ts', {
		path: 'auth/:provider',
		children: [
			appRoute('routes/_auth+/auth.$provider.callback.ts', {
				path: 'callback',
			}),
		],
	}),
	appRoute('routes/_auth+/forgot-password.tsx', {
		path: 'forgot-password',
	}),
	appRoute('routes/_auth+/login.tsx', { path: 'login' }),
	appRoute('routes/_auth+/logout.tsx', { path: 'logout' }),
	appRoute('routes/_auth+/onboarding.tsx', { path: 'onboarding' }),
	appRoute('routes/_auth+/onboarding_.$provider.tsx', {
		path: 'onboarding/:provider',
	}),
	appRoute('routes/_auth+/reset-password.tsx', {
		path: 'reset-password',
	}),
	appRoute('routes/_auth+/signup.tsx', { path: 'signup' }),
	appRoute('routes/_auth+/verify.tsx', { path: 'verify' }),
	appRoute('routes/_home+/_trending.tsx'),
	appRoute('routes/_home+/_upcoming.tsx', {
		children: [
			appRoute('routes/_home+/index.tsx', { index: true }),
			appRoute('routes/_home+/tailwind-preset.ts', {
				path: 'tailwind-preset',
			}),
		],
	}),
	appRoute('routes/_seo+/robots[.]txt.ts', { path: 'robots.txt' }),
	appRoute('routes/_seo+/sitemap[.]xml.ts', { path: 'sitemap.xml' }),
	appRoute('routes/admin+/cache.tsx', { path: 'admin/cache' }),
	appRoute('routes/admin+/catalog.tsx', { path: 'admin/catalog' }),
	appRoute('routes/admin+/cache_.lru.$cacheKey.ts', {
		path: 'admin/cache/lru/:cacheKey',
	}),
	appRoute('routes/admin+/cache_.sqlite.tsx', {
		path: 'admin/cache/sqlite',
		children: [
			appRoute('routes/admin+/cache_.sqlite.$cacheKey.ts', {
				path: ':cacheKey',
			}),
		],
	}),
	appRoute('routes/collections+/index.tsx', { path: 'collections' }),
	appRoute('routes/collections+/new.tsx', { path: 'collections/new' }),
	appRoute('routes/collections+/$collectionId.edit.tsx', {
		path: 'collections/:collectionId/edit',
	}),
	appRoute('routes/collections+/$collectionId.tsx', {
		path: 'collections/:collectionId',
	}),
	appRoute('routes/calendar.tsx', { path: 'calendar' }),
	appRoute('routes/credits.tsx', { path: 'credits' }),
	appRoute('routes/discover.tsx', { path: 'discover' }),
	appRoute('routes/reviews.tsx', { path: 'reviews' }),
	appRoute('routes/lists+/.$username+/.$list-type+/_settings.tsx', {
		path: 'lists/:username/:list-type',
		children: [
			appRoute('routes/lists+/.$username+/.$list-type+/$watchlist.tsx', {
				path: ':watchlist',
			}),
			appRoute('routes/lists+/.$username+/.$list-type+/index.tsx', {
				index: true,
			}),
		],
	}),
	appRoute('routes/lists+/.$username+/index.ts', {
		path: 'lists/:username/',
		index: true,
	}),
	appRoute('routes/lists+/.fetch+/add-favorite.$request.ts', {
		path: 'lists/fetch/add-favorite/:request',
	}),
	appRoute('routes/lists+/.fetch+/add-row.$request.ts', {
		path: 'lists/fetch/add-row/:request',
	}),
	appRoute('routes/lists+/.fetch+/advanced-edit.$request.ts', {
		path: 'lists/fetch/advanced-edit',
	}),
	appRoute('routes/lists+/.fetch+/create-watchlist.$request.ts', {
		path: 'lists/fetch/create-watchlist/:request',
	}),
	appRoute('routes/lists+/.fetch+/delete-empty-rows.$request.ts', {
		path: 'lists/fetch/delete-empty-rows/:request',
	}),
	appRoute('routes/lists+/.fetch+/delete-row.$request.ts', {
		path: 'lists/fetch/delete-row/:request',
	}),
	appRoute('routes/lists+/.fetch+/delete-watchlist.$request.ts', {
		path: 'lists/fetch/delete-watchlist/:request',
	}),
	appRoute('routes/lists+/.fetch+/fix-watchlist-order.$request.ts', {
		path: 'lists/fetch/fix-watchlist-order/:request',
	}),
	appRoute('routes/lists+/.fetch+/get-list-entries.$request.ts', {
		path: 'lists/fetch/get-list-entries/:request',
	}),
	appRoute('routes/lists+/.fetch+/move-row.$request.ts', {
		path: 'lists/fetch/move-row/:request',
	}),
	appRoute('routes/lists+/.fetch+/now-updated.$request.ts', {
		path: 'lists/fetch/now-updated/:request',
	}),
	appRoute('routes/lists+/.fetch+/remove-favorite.$request.ts', {
		path: 'lists/fetch/remove-favorite/:request',
	}),
	appRoute('routes/lists+/.fetch+/reorder-favorite.$request.ts', {
		path: 'lists/fetch/reorder-favorite/:request',
	}),
	appRoute('routes/lists+/.fetch+/reorder-rows.$request.ts', {
		path: 'lists/fetch/reorder-rows/:request',
	}),
	appRoute('routes/lists+/.fetch+/update-cell.$request.ts', {
		path: 'lists/fetch/update-cell/:request',
	}),
	appRoute('routes/lists+/.fetch+/update-row.$request.ts', {
		path: 'lists/fetch/update-row/:request',
	}),
	appRoute('routes/lists+/.fetch+/update-settings.$request.ts', {
		path: 'lists/fetch/update-settings/:request',
	}),
	appRoute('routes/lists+/index.tsx', {
		path: 'lists/',
		index: true,
	}),
	appRoute('routes/me.tsx', { path: 'me' }),
	appRoute('routes/media+/fetch-data.$request.ts', {
		path: 'media/fetch-data/:request',
	}),
	appRoute('routes/media+/mal.ts', { path: 'media/mal' }),
	appRoute('routes/media+/tmdb.ts', { path: 'media/tmdb' }),
	appRoute('routes/media+/$mediaId.tsx', { path: 'media/:mediaId' }),
	appRoute('routes/notifications.tsx', { path: 'notifications' }),
	appRoute('routes/resources+/calendar[.]ics.ts', {
		path: 'resources/calendar.ics',
	}),
	appRoute('routes/resources+/download-user-data.tsx', {
		path: 'resources/download-user-data',
	}),
	appRoute('routes/resources+/follow.ts', {
		path: 'resources/follow',
	}),
	appRoute('routes/resources+/healthcheck.tsx', {
		path: 'resources/healthcheck',
	}),
	appRoute('routes/resources+/lists.v1.ts', {
		path: 'resources/lists/v1',
	}),
	appRoute('routes/resources+/lists.v1.entries.ts', {
		path: 'resources/lists/v1/entries',
	}),
	appRoute('routes/resources+/profile-comment.ts', {
		path: 'resources/profile-comment',
	}),
	appRoute('routes/resources+/quick-track.ts', {
		path: 'resources/quick-track',
	}),
	appRoute('routes/resources+/home-dashboard-preferences.ts', {
		path: 'resources/home-dashboard-preferences',
	}),
	appRoute('routes/resources+/recommendation-feedback.ts', {
		path: 'resources/recommendation-feedback',
	}),
	appRoute('routes/resources+/user-banners.$imageId.tsx', {
		path: 'resources/user-banners/:imageId',
	}),
	appRoute('routes/resources+/user-images.$imageId.tsx', {
		path: 'resources/user-images/:imageId',
	}),
	appRoute('routes/settings+/profile.tsx', {
		path: 'settings/profile',
		children: [
			appRoute('routes/settings+/profile.banner.tsx', {
				path: 'banner',
			}),
			appRoute('routes/settings+/profile.change-email.tsx', {
				path: 'change-email',
			}),
			appRoute('routes/settings+/profile.connections.tsx', {
				path: 'connections',
			}),
			appRoute('routes/settings+/profile.index.tsx', { index: true }),
			appRoute('routes/settings+/profile.notifications.tsx', {
				path: 'notifications',
			}),
			appRoute('routes/settings+/profile.password.tsx', {
				path: 'password',
			}),
			appRoute('routes/settings+/profile.password_.create.tsx', {
				path: 'password/create',
			}),
			appRoute('routes/settings+/profile.photo.tsx', { path: 'photo' }),
			appRoute('routes/settings+/profile.two-factor.tsx', {
				path: 'two-factor',
				children: [
					appRoute('routes/settings+/profile.two-factor.disable.tsx', {
						path: 'disable',
					}),
					appRoute('routes/settings+/profile.two-factor.index.tsx', {
						index: true,
					}),
					appRoute('routes/settings+/profile.two-factor.verify.tsx', {
						path: 'verify',
					}),
				],
			}),
		],
	}),
	appRoute('routes/users+/$username.tsx', {
		path: 'users/:username',
		children: [
			appRoute('routes/users+/$username.activity.tsx', {
				path: 'activity',
			}),
			appRoute('routes/users+/$username.collections.tsx', {
				path: 'collections',
			}),
			appRoute('routes/users+/$username.diary.tsx', {
				path: 'diary',
			}),
			appRoute('routes/users+/$username.favorites.tsx', {
				path: 'favorites',
			}),
			appRoute('routes/users+/$username.index.tsx', { index: true }),
			appRoute('routes/users+/$username.reviews.tsx', {
				path: 'reviews',
			}),
			appRoute('routes/users+/$username.social.tsx', { path: 'social' }),
			appRoute('routes/users+/$username.stats.tsx', { path: 'stats' }),
		],
	}),
	appRoute('routes/users+/$username_/stats_/index.tsx', {
		path: 'users/:username/stats',
	}),
	appRoute('routes/users+/index.tsx', {
		path: 'users/',
		index: true,
	}),
] satisfies RouteConfig
