export const PlantoWatchData = [
  { '#': '1',
  'Thumbnail': 'Picture',
  'Title': 'Before Sunset (Plan to Watch)',
  'Type': 'Movie',
  'Air_Year': '2004',
  'Length': '1h 20m',
  'Rating': 'R',
  'Finished_Date': '6/4/23',
  'Genre(s)': 'Drama, Romance',
  'Language': 'English',
  'Story': '6',
  'Character': '10',
  'Presentation': '5',
  'Sound': '7',
  'Performance': '9',
  'Enjoyment': '10',
  'Averaged': '7.84',
  'Personal': '10',
  'Difference_Personal': '',
  'TMDB_Score': '7.8',
  'Difference_Objective': '' },

  { '#': '2',
  'Thumbnail': 'Picture',
  'Title': 'The Godfather Part II',
  'Type': 'Movie',
  'Air_Year': '1974',
  'Length': '3h 22m',
  'Rating': 'R',
  'Finished_Date': '4/23/23',
  'Genre(s)': 'Crime, Drama',
  'Language': 'English',
  'Story': '7',
  'Character': '8',
  'Presentation': '7',
  'Sound': '8',
  'Performance': '7',
  'Enjoyment': '6',
  'Averaged': '7.17',
  'Personal': '7.2',
  'Difference_Personal': '',
  'TMDB_Score': '8.6',
  'Difference_Objective': '' },

  { '#': '3',
  'Thumbnail': 'Picture',
  'Title': 'Our Little Sister',
  'Type': 'Movie',
  'Air_Year': '2015',
  'Length': '2h 7m',
  'Rating': 'PG',
  'Finished_Date': '6/23/23',
  'Genre(s)': 'Drama, Family',
  'Language': 'Japanese',
  'Story': '3',
  'Character': '6',
  'Presentation': '8',
  'Sound': '8',
  'Performance': '7',
  'Enjoyment': '7',
  'Averaged': '6.5',
  'Personal': '5.4',
  'Difference_Personal': '',
  'TMDB_Score': '7.6',
  'Difference_Objective': '' },

  { '#': '4',
  'Thumbnail': 'Picture',
  'Title': 'Gen V',
  'Type': 'TV Series*',
  'Air_Year': '2023-',
  'Length': '8 / 8 eps',
  'Rating': 'TV-MA',
  'Finished_Date': '7/20/23',
  'Genre(s)': 'Action, Adventure, Comedy',
  'Language': 'English',
  'Story': '4',
  'Character': '4',
  'Presentation': '7',
  'Sound': '6',
  'Performance': '6',
  'Enjoyment': '5',
  'Averaged': '5.34',
  'Personal': '3.4',
  'Difference_Personal': '',
  'TMDB_Score': '8',
  'Difference_Objective': '' },

  { '#': '5',
  'Thumbnail': 'Picture',
  'Title': 'Cunk on Earth',
  'Type': 'TV Series',
  'Air_Year': '2022-2022',
  'Length': '10 / 10 eps',
  'Rating': 'TV-MA',
  'Finished_Date': '3/7/23',
  'Genre(s)': 'Comedy',
  'Language': 'English',
  'Story': '1',
  'Character': '1',
  'Presentation': '6',
  'Sound': '6',
  'Performance': '3',
  'Enjoyment': '2',
  'Averaged': '3.17',
  'Personal': '1.2',
  'Difference_Personal': '',
  'TMDB_Score': '7.8',
  'Difference_Objective': '' }
]
